# Generated by Django 4.2.10 on 2026-01-25 08:43

from django.db import migrations


def delete_all_delivery_slots(apps, schema_editor):
    """Delete all DeliverySlot records before model removal."""
    DeliverySlot = apps.get_model('delivery', 'DeliverySlot')
    count, _ = DeliverySlot.objects.all().delete()
    print(f"Deleted {count} delivery slot records")


def reverse_func(apps, schema_editor):
    """No reverse operation - slots cannot be restored."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_all_delivery_slots, reverse_func),
    ]
