# Generated by Django 4.2.10 on 2026-01-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_delivery_slots_data'),
    ]

    operations = [
        # Remove the foreign key relationship to DeliveryZone
        migrations.RemoveField(
            model_name='deliveryslot',
            name='zone',
        ),
        # Delete the DeliverySlot model and its table
        migrations.DeleteModel(
            name='DeliverySlot',
        ),
    ]
