# Generated by Django 4.2.10 on 2026-01-08 14:56

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('PICKING', 'Picking'), ('PACKED', 'Packed'), ('PROCESSING', 'Processing'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING_CONFIRMATION', max_length=20)),
                ('subtotal', models.BigIntegerField(default=0, help_text='Subtotal in XAF', validators=[django.core.validators.MinValueValidator(0), core.validators.validate_xaf_amount])),
                ('delivery_fee', models.BigIntegerField(default=0, help_text='Delivery fee in XAF', validators=[django.core.validators.MinValueValidator(0), core.validators.validate_xaf_amount])),
                ('total', models.BigIntegerField(default=0, help_text='Total amount in XAF', validators=[django.core.validators.MinValueValidator(0), core.validators.validate_xaf_amount])),
                ('delivery_address_line1', models.CharField(max_length=255)),
                ('delivery_address_line2', models.CharField(blank=True, max_length=255)),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_region', models.CharField(max_length=100)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=20)),
                ('delivery_phone', models.CharField(max_length=15)),
                ('payment_method', models.CharField(default='COD', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Idempotency key to prevent duplicate orders', max_length=100, null=True, unique=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery.deliveryzone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.BigIntegerField(help_text='Price per unit at time of order (XAF)', validators=[django.core.validators.MinValueValidator(0), core.validators.validate_xaf_amount])),
                ('total_price', models.BigIntegerField(help_text='Total price for this item (XAF)', validators=[django.core.validators.MinValueValidator(0), core.validators.validate_xaf_amount])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
            ],
            options={
                'db_table': 'order_items',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_user_id_17dbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['idempotency_key'], name='orders_idempot_dc67bf_idx'),
        ),
    ]
