# Generated by Django 4.2.10 on 2026-01-25 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, help_text='Assigned delivery courier', limit_choices_to={'role': 'COURIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated minutes until delivery', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_status_update',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of last status change'),
        ),
    ]
