# Generated by Django 4.2.10 on 2026-01-25 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0002_order_courier_order_estimated_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Delivery location latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Delivery location longitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use latitude/longitude instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.deliveryzone'),
        ),
    ]
