# Generated by Django 4.2.10 on 2026-01-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('orders', '0003_order_delivery_latitude_order_delivery_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Vendor-level status for this item', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop that fulfills this item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='vendors.shop'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['shop', 'item_status'], name='order_items_shop_id_8e054f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'item_status'], name='order_items_order_i_6ab565_idx'),
        ),
    ]
