# Generated by Django 4.2.10 on 2026-01-25 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('request_type', models.CharField(choices=[('SHOP_OWNER', 'Shop Owner'), ('SUPPLIER', 'Supplier'), ('COURIER', 'Courier'), ('OTHER', 'Other')], db_index=True, default='SHOP_OWNER', max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('business_address', models.TextField()),
                ('business_city', models.CharField(max_length=100)),
                ('business_region', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the business and collaboration interest')),
                ('product_categories', models.TextField(blank=True, help_text='Product categories (comma separated)')),
                ('estimated_products', models.PositiveIntegerField(blank=True, help_text='Estimated number of products', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='collaborati_status_d45617_idx'), models.Index(fields=['request_type', 'status'], name='collaborati_request_f02145_idx'), models.Index(fields=['phone_number'], name='collaborati_phone_n_1f3f3a_idx')],
            },
        ),
    ]
