# Generated by Django 4.2.10 on 2026-01-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_update_user_model_email_or_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin'), ('WAREHOUSE', 'Warehouse'), ('COURIER', 'Courier')], db_index=True, default='CUSTOMER', max_length=20),
        ),
    ]
