# Generated by Django 4.2.10 on 2026-01-08 14:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.IntegerField(default=0, help_text='Available quantity on hand', validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved', models.IntegerField(default=0, help_text='Reserved quantity for pending orders', validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_point', models.IntegerField(default=0, help_text='Reorder point threshold', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item', to='catalog.product')),
            ],
            options={
                'db_table': 'inventory_items',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('ADJUST', 'Adjustment'), ('RETURN_IN', 'Return In'), ('DAMAGED', 'Damaged')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity change (positive for INBOUND/RETURN_IN, negative for OUTBOUND/DAMAGED)')),
                ('reference', models.CharField(blank=True, help_text='Reference (e.g., order number, PO number)', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory_item', 'created_at'], name='stock_movem_invento_74b0be_idx'), models.Index(fields=['movement_type', 'created_at'], name='stock_movem_movemen_d2f919_idx'), models.Index(fields=['reference'], name='stock_movem_referen_de2378_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product'], name='inventory_i_product_33f9bf_idx'),
        ),
    ]
