# Generated by Django 4.2.10 on 2026-01-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop selling this product (required for multi-vendor)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.shop'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active'], name='products_shop_id_ec9b58_idx'),
        ),
    ]
