# Generated by Django 4.2.10 on 2026-01-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_shop_product_products_shop_id_ec9b58_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image', null=True, upload_to='categories/'),
        ),
    ]
