# Generated by Django 4.2.10 on 2026-01-30 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_end_date',
            field=models.DateTimeField(blank=True, help_text='When the sale ends', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.BigIntegerField(blank=True, help_text='Promotional price in XAF. Must be less than regular price.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_start_date',
            field=models.DateTimeField(blank=True, help_text='When the sale starts', null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_on_sale', 'is_active'], name='products_is_on_s_333f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'is_active'], name='products_is_publ_9ea7ec_idx'),
        ),
    ]
