# Generated by Django 4.2.10 on 2026-01-08 14:56

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_amount_xaf', models.BigIntegerField(help_text='Maximum COD amount per day in XAF', validators=[core.validators.validate_xaf_amount])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cod_limit_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Blacklisted phone number', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format +235XXXXXXXX (Chad format)', regex='^\\+235[0-9]{8}$')])),
                ('reason', models.TextField(help_text='Reason for blacklisting')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blacklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blacklists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_active'], name='blacklists_phone_n_f502af_idx')],
            },
        ),
    ]
