# Generated by Django 4.2.10 on 2026-01-08 14:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(db_index=True, help_text='Recipient phone number', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in format +235XXXXXXXX (Chad format)', regex='^\\+235[0-9]{8}$')])),
                ('notification_type', models.CharField(choices=[('ORDER_CONFIRMATION', 'Order Confirmation'), ('ORDER_REMINDER', 'Order Reminder'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_FAILED', 'Order Failed'), ('DELIVERY_ASSIGNED', 'Delivery Assigned'), ('DELIVERY_IN_TRANSIT', 'Delivery In Transit')], db_index=True, max_length=30)),
                ('message', models.TextField(help_text='Notification message')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts')),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Last error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='deliveries.delivery')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
