# Generated by Django 4.2.10 on 2026-02-01 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, help_text='Extra data payload', null=True)),
                ('notification_type', models.CharField(choices=[('order_confirmed', 'Commande confirmee'), ('courier_assigned', 'Livreur assigne'), ('order_picked_up', 'Commande recuperee'), ('order_on_the_way', 'Livreur en route'), ('order_delivered', 'Commande livree'), ('order_cancelled', 'Commande annulee'), ('promotion', 'Promotion'), ('back_in_stock', 'Retour en stock'), ('delivery_assigned', 'Livraison assignee'), ('delivery_cancelled', 'Livraison annulee'), ('address_changed', 'Adresse modifiee'), ('daily_reminder', 'Rappel quotidien')], db_index=True, max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_sent', models.BooleanField(default=False, help_text='Whether FCM send succeeded')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='push_notifi_user_id_a10111_idx'), models.Index(fields=['user', 'notification_type'], name='push_notifi_user_id_9f5fca_idx'), models.Index(fields=['user', 'created_at'], name='push_notifi_user_id_52f102_idx')],
            },
        ),
    ]
